//actions
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
export const USER_REGISTER_REQUESTED = 'USER_REGISTER_REQUESTED';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';
export const USER_ACCESS_REQUESTED = 'USER_ACCESS_REQUESTED';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_FETCH_FAILURE = 'USER_FETCH_FAILURE';
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const SHOW_ERROR = 'SHOW_ERROR';
export const SWITCH_ACTION = 'SWITCH_ACTION';
export const SET_HTTP_CODE = 'SET_HTTP_CODE';
